FROM php:8.3.7-fpm

# Mise à jour des paquets et installation des dépendances
RUN apt-get update && apt-get install -y libpq-dev

# Installation des extensions PHP nécessaires
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli
